name: CI

on:
  pull_request:
    branches: [main]
  push:
  workflow_dispatch:

env:
  DATABASE_URL: postgres://user:password@localhost:5432/db?schema=techstories
  NEXTAUTH_URL: http://localhost:3000
  POSTGRES_PASSWORD: password
  POSTGRES_USER: user
  POSTGRES_DB: db
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  DD_INSIDE_CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # Single compose build with basic caching
      - name: Build and start services
        env:
          DOCKER_BUILDKIT: 1
          COMPOSE_DOCKER_CLI_BUILD: 1
        run: |
          # Build only the quotes_api service (others are pre-built)
          docker compose build --build-arg BUILDKIT_INLINE_CACHE=1 quotes_api
          # Start all services
          docker compose up -d
      - name: Start Services
        run: docker compose up -d
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
      - name: Install Dependencies
        run: npm ci
      - name: Prepare Database
        run: npm run db-prep
      - name: Run All Tests
        id: run_tests
        run: npm run test:ci
        env:
          NODE_ENV: test
          NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
      - name: Stop Services
        if: always()
        run: docker compose down
