name: CI

on:
  pull_request:
    branches: [main]
    # run on open, and on every push
    types: [opened, synchronize]
  push:
  workflow_dispatch:

permissions:
  contents: read
  actions: write # Required for cache operations

env:
  DATABASE_URL: postgres://user:password@localhost:5432/db?schema=techstories
  NEXTAUTH_URL: http://localhost:3000
  POSTGRES_PASSWORD: password
  POSTGRES_USER: user
  POSTGRES_DB: db
  DD_API_KEY: ${{ secrets.DD_API_KEY }}
  DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
  DD_INSIDE_CI: true
  DD_HOSTNAME: ${{ github.workflow }}-${{ github.ref }}
  DD_ENV: CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Build and cache quotes_api
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5.4.0
        with:
          context: ./services/quotes_api
          push: false
          load: true
          tags: quotes_api:latest
          cache-from: type=gha,scope=quotes-api
          cache-to: type=gha,scope=quotes-api,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      # Start all services
      - name: Start Services
        run: docker compose up -d
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Restore node_modules cache
        id: cache
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        if: always()
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Prepare Database
        run: npm run db-prep
      - name: Configure Datadog Test Optimization
        # if datadog api key is not set, skip this step
        if: env.DD_API_KEY != ''
        uses: datadog/test-visibility-github-action@f76512a963e7375dab9ad7f1abc0cacd41806c5c # v2.6.0
        with:
          languages: js
          api_key: ${{ env.DD_API_KEY }}
          site: datadoghq.com
      - name: Run All Tests
        id: run_tests
        run: npm run test:ci
        env:
          NODE_ENV: test
          NEXTAUTH_URL: ${{ env.NEXTAUTH_URL }}
          DATABASE_URL: ${{ env.DATABASE_URL }}
          NODE_OPTIONS: ${{ env.DD_TRACE_PACKAGE && format('-r {0}', env.DD_TRACE_PACKAGE) || '' }}
      - name: Stop Services
        if: always()
        run: docker compose down
      - name: Save npm cache
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        if: always()
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
