name: Run Tests

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Datadog Test Optimization
        uses: datadog/test-visibility-github-action@v2
        with:
          languages: js
          api_key: ${{ env.DD_API_KEY }}
          site: datadoghq.com # Change if your site is not US1
      - name: Start Services
        run: docker compose up -d
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Prepare Database
        run: npm run db-prep
      - name: Run Tests
        run: npm run test:ci
        env:
          NODE_OPTIONS: "-r dd-trace/ci/init"
        continue-on-error: true
      - name: Stop Services
        run: docker compose down
      - name: Print Test Summary
        run: |
          echo "Test Summary:"
          echo "============="
          echo "Total Tests: $(grep -c 'test(' coverage/lcov-report/index.html)"
          echo "Total Coverage: $(grep -oP 'Total coverage: \K[0-9.]+' coverage/lcov-report/index.html)"
          # print to GITHUB_STEP_SUMMARY
          echo "Test Summary: $(grep -oP 'Total coverage: \K[0-9.]+' coverage/lcov-report/index.html)" >> $GITHUB_STEP_SUMMARY
