name: Unit Tests

on:
  pull_request:
    branches: [main]
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run Unit Tests
        run: npm run test:ci
        env:
          DATABASE_URL: postgres://user:password@127.0.0.1:5432/db?schema=techstories
          NEXTAUTH_URL: http://localhost:3000
